version: "3.8"

services:
  aksara:
    container_name: transjawa-aksara
    build: .
    ports:
      - "9001:8090"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

networks:
  default:
    name: transjawa-network
    external: true
